### ISSUE TITLE
problems with angular 1.5

### ISSUE THREAD

**Issue by markus138** [FredrikSandell/angular-workers#18]
hello, there seems to be a problem with angular 1.5

`WorkerService.setAngularUrl('https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.0/angular.min.js');`

causes 

> Script error.

as far as I can tell this happens with every version after 1.4.7

**Comment by JaimeChavarriaga** [comment]
Do you have an example?
I was not able to reproduce the problem.

Previous versions had problems with angular 1.4.7+. Angular requires some methods and attributes. The angular-workers includes now an additional attribute to prevent some problems. Although the version of the module has not changed, maybe you need to download again the files.
